---
"$schema": https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

palette:
  color_fg0: '#fbf1c7'
  color_fg3: '#83a598'
  color_bg1: '#3c3836'
  color_bg3: '#665c54'
  color_blue: '#458588'
  color_dark_blue: '#456988'
  color_aqua: '#689d6a'
  color_green: '#98971a'
  color_orange: '#d65d0e'
  color_bright_orange: '#FF9248'
  color_purple: '#b16286'
  color_red: '#cc241d'
  color_yellow: '#d79921'


blocks:
- alignment: left
  segments:
  - type: os
    properties:
        ubuntu: "󰕈"
    style: diamond
    leading_diamond: ""
      #    trailing_diamond: ""
    background: p:color_orange
    foreground: p:color_fg0
    template: "{{ if .WSL }}WSL at{{ end }}{{.Icon}} "

  - type: session
    style: powerline
    foreground: p:color_fg0
    background: p:color_orange
    trailing_diamond: ""
    template: "{{ if .SSHSession }} {{ end }}{{ .UserName }} "

  - type: path
    background: p:color_yellow
    foreground: p:color_fg0
    powerline_symbol: ""
    properties:
      style: full
    style: powerline
    template: " {{ .Path }} "

  - type: git
    background: p:color_aqua
    background_templates:
    - "{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}"
    - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}"
    - "{{ if gt .Ahead 0 }}#B388FF{{ end }}"
    - "{{ if gt .Behind 0 }}#B388FF{{ end }}"
    foreground: p:color_fg0
    powerline_symbol: ""
    properties:
      branch_template: "{{ trunc 25 .Branch }}"
      fetch_stash_count: true
      fetch_status: true
      branch_icon: " "
      branch_identical_icon: "●"
    style: accordion
    template: " {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if
      .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed)
      (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String
      }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
    trailing_diamond: ""

  - type: kubectl
    background: p:color_dark_blue
    foreground: p:color_fg0
    style: accordion
    powerline_symbol: ""
    template: " 󱃾 {{ .Context }}{{ if .Namespace }} :: {{ .Namespace }}{{ end }} "

  - type: docker
    style: accordion
    powerline_symbol: ""
    background: p:color_bg3
    foreground: p:color_fg3
    tempalte: "{{if .Context}}   {{ .Context }}{{end}} "

  - type: time
    style: diamond
    background: p:color_bg1
    foreground: p:color_fg0
    trailing_diamond: ""
    properties:
      time_format: "15:04"
    template: "  {{ .CurrentDate | date .Format }} "
  type: prompt

- alignment: left
  type: prompt
  newline: true
  segments:
  - type: text
    syle: plain
    foreground_templates:
    - '{{if ne .Code 0}}p:color_red{{end}}'
    - 'p:color_green'
    template: "❯"

transient_prompt:
  #  - background: "transparent"
    # foreground: "p:color_green"
  background: transparent
  foreground_templates:
    - '{{if ne .Code 0}}p:color_red{{end}}'
    - 'p:color_green'
  template: "❯"

console_title_template: "{{ .Folder }}"
final_space: true
version: 3

